// Generated by scripts/ramp.js — do not edit by hand.
//
// The measured colour ramps (plan.md §2.1). Each is 32 equal-population buckets
// of one population of reference pixels, sorted by luminance, so feeding a
// uniformly distributed shading term through one of these reproduces that
// population's own tonal histogram rather than a slide toward grey.
//
// Populations, and what separates them (scripts/ramp.js):
//   water   487925 px  blue and not bright — the tank's own body of water
//   bell     10125 px  strongly warm (r-b>90) — the bells' own body
//   veil     57215 px  bright and not blue — oral arms and tentacles
//
// Stored *inverse-tonemapped into linear HDR*: the composer applies ACES at
// toneMappingExposure = 1.0 and then the sRGB encode once at the end, so
// pre-applying the analytic inverse makes these land back on the measured sRGB.
// Regenerate if the renderer's exposure or tonemapping operator ever changes.
import * as THREE from 'three';

const WATER_HDR = new Float32Array([
  0.01483, 0.04387, 0.12408,
  0.01550, 0.04790, 0.13810,
  0.01598, 0.05037, 0.14510,
  0.01646, 0.05225, 0.14866,
  0.01694, 0.05397, 0.15357,
  0.01741, 0.05574, 0.15682,
  0.01784, 0.05763, 0.16032,
  0.01814, 0.05978, 0.16282,
  0.01860, 0.06179, 0.16592,
  0.01899, 0.06384, 0.16936,
  0.01927, 0.06583, 0.17330,
  0.01962, 0.06761, 0.17773,
  0.01995, 0.06945, 0.18200,
  0.02040, 0.07119, 0.18585,
  0.02072, 0.07314, 0.18904,
  0.02104, 0.07520, 0.19325,
  0.02154, 0.07719, 0.19680,
  0.02218, 0.07939, 0.20204,
  0.02283, 0.08208, 0.20807,
  0.02341, 0.08524, 0.21541,
  0.02378, 0.08885, 0.22586,
  0.02429, 0.09252, 0.23527,
  0.02487, 0.09648, 0.24329,
  0.02538, 0.10115, 0.25290,
  0.02606, 0.10650, 0.26246,
  0.02655, 0.11255, 0.27695,
  0.02789, 0.11862, 0.28711,
  0.02921, 0.12649, 0.30279,
  0.02900, 0.13793, 0.33613,
  0.03011, 0.15095, 0.36746,
  0.03011, 0.16853, 0.40762,
  0.03448, 0.18796, 0.43765,
]);

const BELL_HDR = new Float32Array([
  0.41394, 0.09355, 0.04979,
  0.51368, 0.11415, 0.06044,
  0.59055, 0.12952, 0.06705,
  0.65454, 0.14418, 0.07480,
  0.74595, 0.15403, 0.07483,
  0.78289, 0.16457, 0.08394,
  0.85052, 0.17247, 0.08231,
  0.90754, 0.18112, 0.08461,
  0.91950, 0.19336, 0.09006,
  0.96364, 0.20327, 0.09431,
  1.02918, 0.21206, 0.10083,
  1.04977, 0.22518, 0.10876,
  1.07987, 0.23832, 0.11369,
  1.13993, 0.24595, 0.12418,
  1.22766, 0.25245, 0.12271,
  1.25861, 0.26413, 0.13214,
  1.30110, 0.27502, 0.14178,
  1.36309, 0.28907, 0.13516,
  1.41235, 0.30230, 0.13824,
  1.46530, 0.31069, 0.15020,
  1.51581, 0.32103, 0.15230,
  1.55026, 0.33429, 0.15277,
  1.61742, 0.34483, 0.14844,
  1.67325, 0.35470, 0.15709,
  1.72036, 0.36852, 0.15440,
  1.80271, 0.38501, 0.14556,
  1.85945, 0.40741, 0.14359,
  1.88805, 0.43674, 0.13107,
  1.93902, 0.45864, 0.13551,
  2.03199, 0.48937, 0.13457,
  2.14412, 0.53508, 0.13123,
  2.32880, 0.59086, 0.13346,
]);

const VEIL_HDR = new Float32Array([
  0.17873, 0.19110, 0.30893,
  0.19149, 0.19767, 0.31469,
  0.19971, 0.20542, 0.32565,
  0.21259, 0.21249, 0.33455,
  0.21724, 0.22233, 0.35082,
  0.23413, 0.22998, 0.35710,
  0.25190, 0.23850, 0.36517,
  0.26998, 0.24779, 0.37574,
  0.28329, 0.25863, 0.39275,
  0.31159, 0.26699, 0.39392,
  0.32164, 0.27952, 0.41517,
  0.34166, 0.29082, 0.43364,
  0.35769, 0.30434, 0.45566,
  0.38131, 0.31795, 0.47000,
  0.40306, 0.33242, 0.49012,
  0.43316, 0.34630, 0.50600,
  0.46091, 0.36224, 0.52618,
  0.48641, 0.38017, 0.55630,
  0.52471, 0.39930, 0.57136,
  0.56303, 0.42073, 0.59602,
  0.60578, 0.44349, 0.61309,
  0.64719, 0.46830, 0.65284,
  0.70644, 0.49461, 0.68035,
  0.76809, 0.52665, 0.71028,
  0.82883, 0.56480, 0.75694,
  0.87941, 0.61474, 0.81706,
  0.92366, 0.67921, 0.91330,
  1.04421, 0.75209, 0.91501,
  1.17105, 0.84692, 0.93351,
  1.31830, 0.96877, 1.04673,
  1.52647, 1.14393, 1.43847,
  2.00249, 1.45687, 2.08810,
]);

function rampTexture(hdr: Float32Array): THREE.DataTexture {
  // RGBA rather than RGB: three.js dropped RGBFormat, and WebGL2 will not take
  // a three-channel float texture anyway.
  //
  // **Half** float, and this is the one line standing between the app and a
  // black tank on a phone. Every colour in the picture is a lookup into one of
  // these ramps, so if the lookup returns nothing the whole scene returns
  // nothing — which is exactly what it did: water, bells and veils all at zero,
  // with only the additive rim of a jellyfish left faintly visible.
  //
  // RGBA32F is *not* a filterable format in WebGL2. Sampling one with
  // LinearFilter needs OES_texture_float_linear, which desktop drivers all
  // happen to have and Chrome on Android generally does not; where it is
  // missing the texture is incomplete and every fetch reads black. Nothing in
  // the console says so, and it cannot reproduce on a desktop or in
  // scripts/capture.js's swiftshader, which is why it survived this long.
  //
  // RGBA16F *is* filterable in core WebGL2, everywhere. The ramps are authored
  // in pre-tonemap linear and top out at 6.14, where half float still carries
  // about three decimal digits — far finer than the 8-bit sRGB the values were
  // measured from.
  const n = hdr.length / 3;
  const rgba = new Uint16Array(n * 4);
  for (let i = 0; i < n; i++) {
    rgba[i * 4] = THREE.DataUtils.toHalfFloat(hdr[i * 3]);
    rgba[i * 4 + 1] = THREE.DataUtils.toHalfFloat(hdr[i * 3 + 1]);
    rgba[i * 4 + 2] = THREE.DataUtils.toHalfFloat(hdr[i * 3 + 2]);
    rgba[i * 4 + 3] = THREE.DataUtils.toHalfFloat(1);
  }
  const tex = new THREE.DataTexture(rgba, n, 1, THREE.RGBAFormat, THREE.HalfFloatType);
  tex.minFilter = THREE.LinearFilter;
  tex.magFilter = THREE.LinearFilter;
  tex.wrapS = THREE.ClampToEdgeWrapping;
  tex.needsUpdate = true;
  return tex;
}

/** Sampled with s = 0 at the deepest shadow, 1 at the brightest crown. */
export const waterRamp = () => rampTexture(WATER_HDR);
export const bellRamp = () => rampTexture(BELL_HDR);
export const veilRamp = () => rampTexture(VEIL_HDR);

/** The same lookup on the CPU, for anything that has to agree with the shader
 * without a GPU readback (scripts/*, and the marine snow's tint). */
export function sampleRamp(hdr: Float32Array, s: number): [number, number, number] {
  const n = hdr.length / 3;
  const t = Math.min(n - 1, Math.max(0, s * (n - 1)));
  const i = Math.floor(t), f = t - i, j = Math.min(n - 1, i + 1);
  return [0, 1, 2].map((k) => hdr[i * 3 + k] * (1 - f) + hdr[j * 3 + k] * f) as [number, number, number];
}

export const WATER = WATER_HDR;
export const BELL = BELL_HDR;
export const VEIL = VEIL_HDR;
