// Generated by scripts/ramp.js — do not edit by hand.
//
// The measured colour ramps (plan.md §2.1). Each is 32 equal-population buckets
// of one population of reference pixels, sorted by luminance, so feeding a
// uniformly distributed shading term through one of these reproduces that
// population's own tonal histogram rather than a slide toward grey.
//
// Populations, and what separates them (scripts/ramp.js):
//   water   487907 px  blue and not bright — the tank's own body of water
//   bell     54095 px  warm — the only warm thing in the picture
//   veil     23407 px  bright and not blue — oral arms and tentacles
//
// Stored *inverse-tonemapped into linear HDR*: the composer applies ACES at
// toneMappingExposure = 1.0 and then the sRGB encode once at the end, so
// pre-applying the analytic inverse makes these land back on the measured sRGB.
// Regenerate if the renderer's exposure or tonemapping operator ever changes.
import * as THREE from 'three';

const WATER_HDR = new Float32Array([
  0.01483, 0.04387, 0.12408,
  0.01550, 0.04790, 0.13810,
  0.01598, 0.05037, 0.14510,
  0.01646, 0.05224, 0.14866,
  0.01694, 0.05397, 0.15357,
  0.01741, 0.05574, 0.15682,
  0.01784, 0.05763, 0.16032,
  0.01814, 0.05978, 0.16282,
  0.01860, 0.06179, 0.16592,
  0.01899, 0.06383, 0.16935,
  0.01927, 0.06583, 0.17330,
  0.01962, 0.06762, 0.17774,
  0.01995, 0.06945, 0.18201,
  0.02040, 0.07119, 0.18584,
  0.02072, 0.07314, 0.18904,
  0.02104, 0.07520, 0.19325,
  0.02154, 0.07719, 0.19679,
  0.02218, 0.07938, 0.20201,
  0.02283, 0.08208, 0.20811,
  0.02341, 0.08523, 0.21538,
  0.02378, 0.08884, 0.22586,
  0.02429, 0.09252, 0.23524,
  0.02487, 0.09648, 0.24333,
  0.02539, 0.10114, 0.25284,
  0.02605, 0.10650, 0.26253,
  0.02656, 0.11253, 0.27688,
  0.02789, 0.11861, 0.28707,
  0.02918, 0.12650, 0.30292,
  0.02902, 0.13791, 0.33597,
  0.03009, 0.15097, 0.36753,
  0.03008, 0.16855, 0.40773,
  0.03449, 0.18795, 0.43761,
]);

const BELL_HDR = new Float32Array([
  0.15004, 0.08727, 0.12494,
  0.16541, 0.09991, 0.14091,
  0.18414, 0.11294, 0.15612,
  0.21243, 0.12600, 0.16623,
  0.24091, 0.13901, 0.17775,
  0.26239, 0.15329, 0.19316,
  0.28728, 0.16660, 0.20748,
  0.31970, 0.17898, 0.21698,
  0.35526, 0.19153, 0.22082,
  0.39722, 0.20342, 0.22387,
  0.43423, 0.21626, 0.23299,
  0.47573, 0.22865, 0.23850,
  0.49611, 0.24307, 0.25842,
  0.52851, 0.25720, 0.27163,
  0.55999, 0.27286, 0.28521,
  0.59771, 0.28883, 0.29529,
  0.63921, 0.30361, 0.31007,
  0.68094, 0.31930, 0.32084,
  0.72067, 0.33597, 0.33868,
  0.78516, 0.35339, 0.33971,
  0.87519, 0.36779, 0.33489,
  0.94715, 0.38623, 0.33875,
  1.02147, 0.40544, 0.34035,
  1.09298, 0.42783, 0.35943,
  1.16320, 0.45661, 0.37266,
  1.26863, 0.48809, 0.36467,
  1.35074, 0.52375, 0.41874,
  1.47218, 0.57456, 0.44178,
  1.61150, 0.64243, 0.50679,
  1.86251, 0.73726, 0.57397,
  2.14874, 0.88552, 0.73378,
  2.63056, 1.15906, 1.26979,
]);

const VEIL_HDR = new Float32Array([
  0.13475, 0.19863, 0.35649,
  0.13943, 0.20376, 0.36575,
  0.14354, 0.20966, 0.37137,
  0.14742, 0.21559, 0.38129,
  0.15277, 0.22095, 0.39351,
  0.15545, 0.22786, 0.40749,
  0.16117, 0.23436, 0.41893,
  0.16729, 0.24132, 0.42577,
  0.17468, 0.24781, 0.44246,
  0.17939, 0.25696, 0.45589,
  0.18707, 0.26596, 0.47325,
  0.19191, 0.27655, 0.49620,
  0.20028, 0.28721, 0.50851,
  0.20929, 0.29878, 0.53177,
  0.22086, 0.31025, 0.55390,
  0.23309, 0.32234, 0.58041,
  0.24012, 0.33770, 0.62511,
  0.25148, 0.35432, 0.65864,
  0.26309, 0.37195, 0.70177,
  0.26608, 0.39619, 0.77551,
  0.28316, 0.41867, 0.84310,
  0.29766, 0.44731, 0.91344,
  0.30506, 0.48231, 1.03282,
  0.31981, 0.51677, 1.15022,
  0.33283, 0.55735, 1.33005,
  0.34245, 0.61123, 1.52049,
  0.34066, 0.67764, 1.83907,
  0.33667, 0.76026, 2.26430,
  0.32338, 0.86372, 2.82161,
  0.29855, 0.99745, 3.62429,
  0.30318, 1.19527, 4.68571,
  0.40902, 1.55817, 6.14391,
]);

function rampTexture(hdr: Float32Array): THREE.DataTexture {
  // RGBA rather than RGB: three.js dropped RGBFormat, and WebGL2 will not take
  // a three-channel float texture anyway.
  //
  // **Half** float, and this is the one line standing between the app and a
  // black tank on a phone. Every colour in the picture is a lookup into one of
  // these ramps, so if the lookup returns nothing the whole scene returns
  // nothing — which is exactly what it did: water, bells and veils all at zero,
  // with only the additive rim of a jellyfish left faintly visible.
  //
  // RGBA32F is *not* a filterable format in WebGL2. Sampling one with
  // LinearFilter needs OES_texture_float_linear, which desktop drivers all
  // happen to have and Chrome on Android generally does not; where it is
  // missing the texture is incomplete and every fetch reads black. Nothing in
  // the console says so, and it cannot reproduce on a desktop or in
  // scripts/capture.js's swiftshader, which is why it survived this long.
  //
  // RGBA16F *is* filterable in core WebGL2, everywhere. The ramps are authored
  // in pre-tonemap linear and top out at 6.14, where half float still carries
  // about three decimal digits — far finer than the 8-bit sRGB the values were
  // measured from.
  const n = hdr.length / 3;
  const rgba = new Uint16Array(n * 4);
  for (let i = 0; i < n; i++) {
    rgba[i * 4] = THREE.DataUtils.toHalfFloat(hdr[i * 3]);
    rgba[i * 4 + 1] = THREE.DataUtils.toHalfFloat(hdr[i * 3 + 1]);
    rgba[i * 4 + 2] = THREE.DataUtils.toHalfFloat(hdr[i * 3 + 2]);
    rgba[i * 4 + 3] = THREE.DataUtils.toHalfFloat(1);
  }
  const tex = new THREE.DataTexture(rgba, n, 1, THREE.RGBAFormat, THREE.HalfFloatType);
  tex.minFilter = THREE.LinearFilter;
  tex.magFilter = THREE.LinearFilter;
  tex.wrapS = THREE.ClampToEdgeWrapping;
  tex.needsUpdate = true;
  return tex;
}

/** Sampled with s = 0 at the deepest shadow, 1 at the brightest crown. */
export const waterRamp = () => rampTexture(WATER_HDR);
export const bellRamp = () => rampTexture(BELL_HDR);
export const veilRamp = () => rampTexture(VEIL_HDR);

/** The same lookup on the CPU, for anything that has to agree with the shader
 * without a GPU readback (scripts/*, and the marine snow's tint). */
export function sampleRamp(hdr: Float32Array, s: number): [number, number, number] {
  const n = hdr.length / 3;
  const t = Math.min(n - 1, Math.max(0, s * (n - 1)));
  const i = Math.floor(t), f = t - i, j = Math.min(n - 1, i + 1);
  return [0, 1, 2].map((k) => hdr[i * 3 + k] * (1 - f) + hdr[j * 3 + k] * f) as [number, number, number];
}

export const WATER = WATER_HDR;
export const BELL = BELL_HDR;
export const VEIL = VEIL_HDR;
