#!/usr/bin/env node
/**
 * Measures the picture's colour ramps out of the reference and writes
 * app/src/scene/ramps.ts.
 *
 * plan.md §2.1: shading here indexes a measured ramp instead of scaling a
 * brightness. The method is sakura's cloudRamp.ts, and so is the reason for it —
 * in the reference the *hue is a function of the value*. The water's shadows do
 * not slide toward grey as they darken, they go bluer and deeper; the bells do
 * not slide toward grey either, they go from a white-hot crown through amber to
 * a dark rose. Multiplying an albedo by an N.L term cannot produce either.
 *
 * Indexing by *population* rather than by luminance is what makes a uniformly
 * distributed shading term reproduce the reference's own tonal histogram. So
 * each ramp is 32 equal-population buckets of the pixels that belong to it,
 * sorted by luminance, and each entry is that bucket's mean colour.
 *
 * The three populations are separated the same way the plate is (scripts/
 * plate.js): geometry first, then morphology — never a hand-picked box.
 *
 *   node scripts/ramp.js            # print the ramps
 *   node scripts/ramp.js --write    # + app/src/scene/ramps.ts
 */
const sharp = require('sharp');
const path = require('path');
const fs = require('fs');
const { srgbToHdr, hdrToSrgb } = require('./hdr');

const { REF, tank } = require('./reference');
const OUT = path.join(__dirname, '..', 'app', 'src', 'scene', 'ramps.ts');
const TANK = tank();
const STEPS = 32;

const lumOf = (r, g, b) => 0.2126 * r + 0.7152 * g + 0.0722 * b;

/** Equal-population ramp: sort by luminance, average each bucket, drop the
 * outermost 2% at both ends where stray pixels of the neighbouring population
 * bleed in. */
function ramp(pixels) {
  pixels.sort((a, b) => a[3] - b[3]);
  const lo = Math.floor(pixels.length * 0.02), hi = Math.ceil(pixels.length * 0.98);
  const use = pixels.slice(lo, hi);
  const out = [];
  for (let i = 0; i < STEPS; i++) {
    const a = Math.floor((i * use.length) / STEPS), b = Math.floor(((i + 1) * use.length) / STEPS);
    let r = 0, g = 0, bl = 0;
    for (let k = a; k < b; k++) { r += use[k][0]; g += use[k][1]; bl += use[k][2]; }
    const n = Math.max(1, b - a);
    out.push([r / n, g / n, bl / n]);
  }
  return out;
}

async function main() {
  const { data, info } = await sharp(REF).raw().toBuffer({ resolveWithObject: true });
  const { width: W, height: H, channels: C } = info;
  const px = (i) => [data[i * C], data[i * C + 1], data[i * C + 2]];

  // Inside the water, with the acrylic wall and both discs excluded — the same
  // region scripts/plate.js punches, shrunk a little further so no rim pixel
  // can reach a ramp.
  const inside = new Uint8Array(W * H);
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      const u = (x - TANK.x0) / (TANK.R - 30);
      if (Math.abs(u) >= 1) continue;
      const f = Math.sqrt(Math.max(0, 1 - u * u));
      if (y > TANK.topYc + TANK.topB * f + 24 && y < TANK.botYc + TANK.botB * f - 50) inside[y * W + x] = 1;
    }
  }

  const water = [], bell = [], veil = [];
  for (let i = 0; i < W * H; i++) {
    if (!inside[i]) continue;
    const [r, g, b] = px(i);
    const L = lumOf(r, g, b);
    if (r > g && r > 90) {
      // The bells: the only warm thing in a picture that is otherwise blue.
      bell.push([r, g, b, L]);
    } else if (L > 130 && b - r < 90) {
      // The oral arms and tentacles: bright, and far less blue than water of
      // the same brightness, because they are lit rather than transmitted.
      veil.push([r, g, b, L]);
    } else if (b - r > 45 && L < 130) {
      water.push([r, g, b, L]);
    }
  }

  const ramps = { water: ramp(water), bell: ramp(bell), veil: ramp(veil) };
  const counts = { water: water.length, bell: bell.length, veil: veil.length };
  for (const [name, r] of Object.entries(ramps)) {
    console.log(`\n${name}  (${counts[name]} px, ${(100 * counts[name] / (W * H)).toFixed(2)}% of frame)`);
    for (let i = 0; i < STEPS; i += 4) {
      const [a, b, c] = r[i];
      console.log(`  s=${(i / (STEPS - 1)).toFixed(3)}  rgb(${a.toFixed(0).padStart(3)},${b.toFixed(0).padStart(3)},${c.toFixed(0).padStart(3)})  b-r ${(c - a).toFixed(0)}`);
    }
  }

  if (!process.argv.includes('--write')) return;

  const table = (r) => r.map((c) => {
    const hdr = srgbToHdr(c);
    return '  ' + hdr.map((v) => v.toFixed(5)).join(', ') + ',';
  }).join('\n');

  const src = `// Generated by scripts/ramp.js — do not edit by hand.
//
// The measured colour ramps (plan.md §2.1). Each is 32 equal-population buckets
// of one population of reference pixels, sorted by luminance, so feeding a
// uniformly distributed shading term through one of these reproduces that
// population's own tonal histogram rather than a slide toward grey.
//
// Populations, and what separates them (scripts/ramp.js):
//   water  ${String(counts.water).padStart(7)} px  blue and not bright — the tank's own body of water
//   bell   ${String(counts.bell).padStart(7)} px  warm — the only warm thing in the picture
//   veil   ${String(counts.veil).padStart(7)} px  bright and not blue — oral arms and tentacles
//
// Stored *inverse-tonemapped into linear HDR*: the composer applies ACES at
// toneMappingExposure = 1.0 and then the sRGB encode once at the end, so
// pre-applying the analytic inverse makes these land back on the measured sRGB.
// Regenerate if the renderer's exposure or tonemapping operator ever changes.
import * as THREE from 'three';

const WATER_HDR = new Float32Array([
${table(ramps.water)}
]);

const BELL_HDR = new Float32Array([
${table(ramps.bell)}
]);

const VEIL_HDR = new Float32Array([
${table(ramps.veil)}
]);

function rampTexture(hdr: Float32Array): THREE.DataTexture {
  // RGBA rather than RGB: three.js dropped RGBFormat, and WebGL2 will not take
  // a three-channel float texture anyway.
  //
  // **Half** float, and this is the one line standing between the app and a
  // black tank on a phone. Every colour in the picture is a lookup into one of
  // these ramps, so if the lookup returns nothing the whole scene returns
  // nothing — which is exactly what it did: water, bells and veils all at zero,
  // with only the additive rim of a jellyfish left faintly visible.
  //
  // RGBA32F is *not* a filterable format in WebGL2. Sampling one with
  // LinearFilter needs OES_texture_float_linear, which desktop drivers all
  // happen to have and Chrome on Android generally does not; where it is
  // missing the texture is incomplete and every fetch reads black. Nothing in
  // the console says so, and it cannot reproduce on a desktop or in
  // scripts/capture.js's swiftshader, which is why it survived this long.
  //
  // RGBA16F *is* filterable in core WebGL2, everywhere. The ramps are authored
  // in pre-tonemap linear and top out at 6.14, where half float still carries
  // about three decimal digits — far finer than the 8-bit sRGB the values were
  // measured from.
  const n = hdr.length / 3;
  const rgba = new Uint16Array(n * 4);
  for (let i = 0; i < n; i++) {
    rgba[i * 4] = THREE.DataUtils.toHalfFloat(hdr[i * 3]);
    rgba[i * 4 + 1] = THREE.DataUtils.toHalfFloat(hdr[i * 3 + 1]);
    rgba[i * 4 + 2] = THREE.DataUtils.toHalfFloat(hdr[i * 3 + 2]);
    rgba[i * 4 + 3] = THREE.DataUtils.toHalfFloat(1);
  }
  const tex = new THREE.DataTexture(rgba, n, 1, THREE.RGBAFormat, THREE.HalfFloatType);
  tex.minFilter = THREE.LinearFilter;
  tex.magFilter = THREE.LinearFilter;
  tex.wrapS = THREE.ClampToEdgeWrapping;
  tex.needsUpdate = true;
  return tex;
}

/** Sampled with s = 0 at the deepest shadow, 1 at the brightest crown. */
export const waterRamp = () => rampTexture(WATER_HDR);
export const bellRamp = () => rampTexture(BELL_HDR);
export const veilRamp = () => rampTexture(VEIL_HDR);

/** The same lookup on the CPU, for anything that has to agree with the shader
 * without a GPU readback (scripts/*, and the marine snow's tint). */
export function sampleRamp(hdr: Float32Array, s: number): [number, number, number] {
  const n = hdr.length / 3;
  const t = Math.min(n - 1, Math.max(0, s * (n - 1)));
  const i = Math.floor(t), f = t - i, j = Math.min(n - 1, i + 1);
  return [0, 1, 2].map((k) => hdr[i * 3 + k] * (1 - f) + hdr[j * 3 + k] * f) as [number, number, number];
}

export const WATER = WATER_HDR;
export const BELL = BELL_HDR;
export const VEIL = VEIL_HDR;
`;
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, src);
  // The same tables in a form the node-side model can read, so scripts/
  // watermodel.js is fitting against exactly the ramp the shader samples.
  fs.writeFileSync(path.join(__dirname, 'ramps.json'), JSON.stringify({
    water: ramps.water.map(srgbToHdr),
    bell: ramps.bell.map(srgbToHdr),
    veil: ramps.veil.map(srgbToHdr),
  }));
  console.log(`\nwrote ${path.relative(process.cwd(), OUT)}`);
  // Round-trip check, so a broken conversion cannot reach the app silently.
  const back = hdrToSrgb(srgbToHdr(ramps.water[16]));
  console.log(`round trip water[16]: ${ramps.water[16].map((v) => v.toFixed(1))} -> ${back.map((v) => v.toFixed(1))}`);
}
main();
