/**
 * The one place that names the reference image and the tank measured out of it.
 *
 * sakura's scripts/README.md opens with a warning worth taking seriously: its
 * reference was replaced once, several shader constants stayed fitted to the
 * *old* image's numbers long after it was deleted, and comments went on quoting
 * statistics nobody could reproduce. The defence here is that no script names
 * the file or the geometry itself — they all read it from here, and the
 * geometry is regenerated by `node scripts/geom.js --write`.
 */
const fs = require('fs');
const path = require('path');

/** The reference illustration. Replacing it means rerunning, in this order:
 * geom.js --write, ramp.js --write, plate.js, then refitting water.ts with
 * watermodel.js --solve. */
const REF = path.join(__dirname, '..', '1786667042546.png');

const TANK_FILE = path.join(__dirname, 'tank.json');

function tank() {
  if (!fs.existsSync(TANK_FILE)) {
    throw new Error('scripts/tank.json is missing — run `node scripts/geom.js --write` first');
  }
  return JSON.parse(fs.readFileSync(TANK_FILE, 'utf8'));
}

module.exports = { REF, TANK_FILE, tank };
