// Generated by scripts/geom.js — do not edit by hand.
//
// The tank, measured off 1786667042546.png. Rerun
// `node scripts/geom.js --write` after replacing the reference.
export const MEASURED = {
  /** The reference frame. Every fitted constant in this project is in these
   * pixels (scripts/README.md). */
  frameWidth: 896,
  frameHeight: 1200,
  /** The cylinder's screen axis and radius. */
  x0: 449.00,
  R: 352.00,
  /** The two ellipses: centre row, and semi-minor axis. */
  topYc: 110.01,
  topB: 59.11,
  botYc: 1106.90,
  botB: 50.02,
  /** Focal length in frame pixels and the principal point's row, solved from
   * the ellipses rather than picked. */
  focal: 3176.0,
  principalY: 651.0,
  /** In tank radii — the scene has no other length scale. */
  eyeDistance: 9.023,
  tankHeight: 2.832,
  eyeHeight: 1.295,
  /** The standpipe, from its edges in a median-of-column profile. */
  pipeRadius: 0.205,
} as const;
